name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Run deployment commands
        run: |
          echo "Deploying to AWS server..."
          ssh -o StrictHostKeyChecking=no -i /tmp/aws_key.pem ubuntu@ec2-13-201-134-80.ap-south-1.compute.amazonaws.com << 'EOF'
          cd grabbzo-web
          git pull --no-rebase origin main
          npm install
          npm run build
          pm2 restart all
          EOF
        env:
          AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Clean up SSH key
        run: rm -f /tmp/aws_key.pem
